version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yahoo_dataset
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql  # AGREGAR ESTA LÍNEA
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yahoo_dataset"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - yahoo_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - yahoo_network

  csv_loader:
    build:
      context: ./loader
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=yahoo_dataset
      - CSV_PATH=/data/test.csv
      - TABLE_NAME=yahoo_answers
    volumes:
      - ./Dataset-Documentation:/data:ro
    networks:
      - yahoo_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=5m
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - yahoo_network

  llm:
    build: ./llm
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:1b
      - REQUEST_TIMEOUT=60
    ports:
      - "5000:5000"
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - yahoo_network

  score:
    build: ./score
    ports:
      - "6000:6000"
    environment:
      - PORT=6000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:6000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - yahoo_network

  cache:
    build: ./cache
    ports:
      - "5002:5002"
    environment:
      - CACHE_SIZE=100
      - CACHE_POLICY=LRU
      - CACHE_TTL=3600
      - LLM_SERVICE_URL=http://llm:5000/ask
      - SCORE_SERVICE_URL=http://score:6000/score  # CAMBIAR DE 5001 A 6000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
    depends_on:
      postgres:
        condition: service_healthy
      llm:
        condition: service_healthy
      score:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5002/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - yahoo_network

  dataset:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
    depends_on:
      - postgres
      - llm
    networks:
      - yahoo_network

  storage: # almacenamiento
    build: ./storage
    ports:
      - "7000:7000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:7000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
      
  traffic-poisson:
    build: ./traffic-generator
    restart: "no"
    profiles: ["poisson"]
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
      - CACHE_SERVICE_URL=http://cache:5002/query  # CAMBIO AQUÍ
      - DISTRIBUTION_TYPE=poisson
      - LAMBDA=5
      - TOTAL_QUERIES=100
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_healthy  # CAMBIO AQUÍ
    networks:
      - yahoo_network

  traffic-uniform:
    build: ./traffic-generator
    restart: "no"
    profiles: ["uniform"]
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
      - CACHE_SERVICE_URL=http://cache:5002/query  # CAMBIO AQUÍ
      - DISTRIBUTION_TYPE=uniform
      - MIN_INTERVAL=100
      - MAX_INTERVAL=2000
      - TOTAL_QUERIES=100
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_healthy  # CAMBIO AQUÍ
    networks:
      - yahoo_network

volumes:
  postgres_data:
  node_modules:
  pgadmin_data:
  ollama_data:

networks:
  yahoo_network:
    driver: bridge