version: "3.8"

services:
  dataset:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - postgres
      - llm

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yahoo_dataset
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yahoo_dataset"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  csv_loader:
    build:
      context: ./loader
    restart: "no"
    depends_on:
      - postgres
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=yahoo_dataset
      - CSV_PATH=/data/test.csv
      - TABLE_NAME=yahoo_answers
    volumes:
      - ./Dataset-Documentation:/data:ro

  llm:
    build: ./llm
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  traffic-poisson: # generador de tr치fico con distribuci칩n de poisson
    build: ./traffic-generator
    restart: "no"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
      - LLM_SERVICE_URL=http://llm:5000/ask
      - DISTRIBUTION_TYPE=poisson
      - LAMBDA=5
      - TOTAL_QUERIES=100
    depends_on:
      postgres:
        condition: service_healthy
      llm:
        condition: service_healthy
    profiles: # se ocupa perfil para ejecutarlo
      - poisson

  traffic-uniform: # generador de tr치fico con distribuci칩n uniforme
    build: ./traffic-generator
    restart: "no"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=yahoo_dataset
      - LLM_SERVICE_URL=http://llm:5000/ask
      - DISTRIBUTION_TYPE=uniform
      - MIN_INTERVAL=100
      - MAX_INTERVAL=2000
      - TOTAL_QUERIES=100
    depends_on:
      postgres:
        condition: service_healthy
      llm:
        condition: service_healthy
    profiles:
      - uniform # perfil uniforme

volumes:
  postgres_data:
  node_modules:
  pgadmin_data:
